p8105_hw2_yy3662
================
Yunyi Yang
2025-09-29

# Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(skimr)
p1task1 <- read.csv(file = "./Data/fivethirtyeight_datasets/pols-month.csv",
                  ,na = c(".", "NA", "")) |>
  separate(mon, c("year", "month", "day"), convert = TRUE) |>
  mutate(month = month.name[month]) |>
  pivot_longer(cols = c(prez_dem, prez_gop), names_to = "parties", values_to = "president") |>
  select(-day)



p1task2 <- read.csv(file = "./Data/fivethirtyeight_datasets/snp.csv",
                  ,na = c(".", "NA", ""))
p1task2$date <- as.Date(p1task2$date, "%d/%m/%y")
p1task2$date <-as.character(p1task2$date)
p1task2 <- separate(p1task2, date, c("year", "month", "day"), convert = TRUE) |>
  mutate(p1task2, month = month.name[month]) |>
  select(-date) # I find date is unnecessary in final dataset
p1task2$year[which(p1task2$year > 2025)] <- p1task2$year[which(p1task2$year > 2025)] - 100L
# because some dates are incorrect because of basic logic of as.Date, so we convert some years like 2065 back to 1965.


p1task3 <- read.csv(file = "./Data/fivethirtyeight_datasets/unemployment.csv",
                  ,na = c(".", "NA", "")) |>
  pivot_longer(Jan:Dec, names_to = "month", values_to = "unemployment") |>
  mutate(month = month.name[match(tolower(month), tolower(month.abb))]) |>
  rename(year = "Year")

join1 <- full_join(p1task1, p1task2, by = c("year", "month"))
```

    ## Warning in full_join(p1task1, p1task2, by = c("year", "month")): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 73 of `x` matches multiple rows in `y`.
    ## ℹ Row 776 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

``` r
join2 <- left_join(join1, p1task3, by = c("year", "month"))
skimr::skim(join2)
```

|                                                  |       |
|:-------------------------------------------------|:------|
| Name                                             | join2 |
| Number of rows                                   | 2782  |
| Number of columns                                | 13    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |       |
| Column type frequency:                           |       |
| character                                        | 2     |
| numeric                                          | 11    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |       |
| Group variables                                  | None  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| month         |         0 |             1 |   3 |   9 |     0 |       12 |          0 |
| parties       |         0 |             1 |   8 |   8 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| year | 0 | 1.00 | 1981.39 | 19.46 | 1947.00 | 1965.00 | 1981.00 | 1998.00 | 2015.00 | ▇▇▇▇▇ |
| gov_gop | 0 | 1.00 | 22.49 | 5.71 | 12.00 | 18.00 | 22.00 | 28.00 | 34.00 | ▆▇▇▆▅ |
| sen_gop | 0 | 1.00 | 46.01 | 6.40 | 32.00 | 42.00 | 46.00 | 51.00 | 56.00 | ▃▃▇▇▇ |
| rep_gop | 0 | 1.00 | 194.36 | 28.74 | 141.00 | 176.00 | 195.00 | 222.00 | 253.00 | ▃▇▆▃▅ |
| gov_dem | 0 | 1.00 | 27.19 | 5.96 | 17.00 | 22.00 | 28.00 | 33.00 | 41.00 | ▆▅▇▆▂ |
| sen_dem | 0 | 1.00 | 54.47 | 7.38 | 44.00 | 48.00 | 54.00 | 58.00 | 71.00 | ▇▆▇▃▂ |
| rep_dem | 0 | 1.00 | 245.26 | 31.27 | 188.00 | 211.00 | 250.00 | 268.00 | 301.00 | ▇▂▇▇▅ |
| president | 0 | 1.00 | 0.50 | 0.50 | 0.00 | 0.00 | 0.50 | 1.00 | 2.00 | ▇▁▇▁▁ |
| day | 1208 | 0.57 | 6.48 | 3.45 | 1.00 | 3.00 | 6.00 | 9.00 | 12.00 | ▇▅▅▅▇ |
| close | 1208 | 0.57 | 474.89 | 545.78 | 17.05 | 83.67 | 138.53 | 944.54 | 2107.39 | ▇▁▂▁▁ |
| unemployment | 24 | 0.99 | 5.84 | 1.63 | 2.50 | 4.70 | 5.70 | 6.90 | 10.80 | ▃▇▅▂▁ |

``` r
summary(join2)
```

    ##       year         month              gov_gop         sen_gop     
    ##  Min.   :1947   Length:2782        Min.   :12.00   Min.   :32.00  
    ##  1st Qu.:1965   Class :character   1st Qu.:18.00   1st Qu.:42.00  
    ##  Median :1981   Mode  :character   Median :22.00   Median :46.00  
    ##  Mean   :1981                      Mean   :22.49   Mean   :46.01  
    ##  3rd Qu.:1998                      3rd Qu.:28.00   3rd Qu.:51.00  
    ##  Max.   :2015                      Max.   :34.00   Max.   :56.00  
    ##                                                                   
    ##     rep_gop         gov_dem         sen_dem         rep_dem     
    ##  Min.   :141.0   Min.   :17.00   Min.   :44.00   Min.   :188.0  
    ##  1st Qu.:176.0   1st Qu.:22.00   1st Qu.:48.00   1st Qu.:211.0  
    ##  Median :195.0   Median :28.00   Median :54.00   Median :250.0  
    ##  Mean   :194.4   Mean   :27.19   Mean   :54.47   Mean   :245.3  
    ##  3rd Qu.:222.0   3rd Qu.:33.00   3rd Qu.:58.00   3rd Qu.:268.0  
    ##  Max.   :253.0   Max.   :41.00   Max.   :71.00   Max.   :301.0  
    ##                                                                 
    ##    parties            president           day             close        
    ##  Length:2782        Min.   :0.0000   Min.   : 1.000   Min.   :  17.05  
    ##  Class :character   1st Qu.:0.0000   1st Qu.: 3.000   1st Qu.:  83.67  
    ##  Mode  :character   Median :0.5000   Median : 6.000   Median : 138.53  
    ##                     Mean   :0.5018   Mean   : 6.478   Mean   : 474.89  
    ##                     3rd Qu.:1.0000   3rd Qu.: 9.000   3rd Qu.: 944.54  
    ##                     Max.   :2.0000   Max.   :12.000   Max.   :2107.39  
    ##                                      NA's   :1208     NA's   :1208     
    ##   unemployment   
    ##  Min.   : 2.500  
    ##  1st Qu.: 4.700  
    ##  Median : 5.700  
    ##  Mean   : 5.844  
    ##  3rd Qu.: 6.900  
    ##  Max.   :10.800  
    ##  NA's   :24

pols-month which names p1task1 contains 822 observations of 9 variables
related to the number of national politicians who are democratic or
republican at any given time: mon: date of the count prez_gop: indicator
of whether the president was republican on the associated date (1 = yes,
0 = no) gov_gop: the number of republican governors on the associated
date sen_gop: the number of republican senators on the associated date
rep_gop: the number of republican representatives on the associated date
prez_dem: indicator of whether the president was democratic on the
associated date (1 = yes, 0 = no) gov_dem: the number of democratic
governors on the associated date sen_dem: the number of democratic
senators on the associated date rep_dem: the number of democratic
representatives on the associated date

snp which names p1task2 contains 787 observations of 2 variables related
to Standard & Poor’s stock market index (S&P), often used as a
representative measure of stock market as a whole: date: the date of the
observation close: the closing values of the S&P stock index on the
associated date

unemployment which names p1task3 contains 3 variables: year: year of
measurement month: month of measurement unemployment: the percentage of
unemployment of specific year and month

In our final dataset, we have 2782 observations and 13 variables, where
contains year, month, day, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem,
rep_dem, parties which shows two options of parties, and president shows
which party is president from at that year, close, unemployment. The
year range is from 1947-01 to 2015-06.

# Problem 2

``` r
library(readxl)
mrtrash <- read_excel("./Data/202509 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N653")
mrtrash <- janitor::clean_names(mrtrash) |>
  mutate(mrtrash$name, name = "mrtrash")
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `mrtrash$name`.
    ## Caused by warning:
    ## ! Unknown or uninitialised column: `name`.

``` r
mrtrash$sports_balls <- as.integer(round(mrtrash$sports_balls))

professor <- read_excel("./Data/202509 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M120")
professor <- janitor::clean_names(professor) |>
  mutate(professor$name, name = "professor")
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `professor$name`.
    ## Caused by warning:
    ## ! Unknown or uninitialised column: `name`.

``` r
Gwynnda <- read_excel("./Data/202509 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:L265")
Gwynnda <- janitor::clean_names(Gwynnda) |>
  mutate(Gwynnda$name, name = "Gwynnda")
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `Gwynnda$name`.
    ## Caused by warning:
    ## ! Unknown or uninitialised column: `name`.

``` r
mrtrash$year <- as.numeric(mrtrash$year) #mrtrash's year variable is not numeric as professor and Gwynnda
join3 <- bind_rows(mrtrash, professor, Gwynnda)
skimr::skim(join3)
```

|                                                  |       |
|:-------------------------------------------------|:------|
| Name                                             | join3 |
| Number of rows                                   | 1032  |
| Number of columns                                | 15    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |       |
| Column type frequency:                           |       |
| character                                        | 2     |
| numeric                                          | 12    |
| POSIXct                                          | 1     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |       |
| Group variables                                  | None  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| month         |         0 |             1 |   3 |   9 |     0 |       14 |          0 |
| name          |         0 |             1 |   7 |   9 |     0 |        3 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| dumpster | 0 | 1.00 | 245.85 | 187.85 | 1.00 | 86.00 | 199.00 | 393.25 | 651.00 | ▇▆▃▃▃ |
| year | 0 | 1.00 | 2019.84 | 2.90 | 2014.00 | 2018.00 | 2020.00 | 2022.00 | 2024.00 | ▅▆▅▇▆ |
| weight_tons | 0 | 1.00 | 3.04 | 0.79 | 0.61 | 2.54 | 3.08 | 3.55 | 5.62 | ▁▃▇▃▁ |
| volume_cubic_yards | 0 | 1.00 | 15.08 | 1.29 | 5.00 | 15.00 | 15.00 | 15.00 | 20.00 | ▁▁▁▇▁ |
| plastic_bottles | 1 | 1.00 | 2201.31 | 1634.80 | 0.00 | 980.00 | 1900.00 | 2900.00 | 9830.00 | ▇▆▁▁▁ |
| polystyrene | 1 | 1.00 | 1383.05 | 1813.67 | 0.00 | 230.00 | 640.00 | 2045.00 | 11528.00 | ▇▂▁▁▁ |
| cigarette_butts | 1 | 1.00 | 13295.92 | 23690.78 | 0.00 | 2800.00 | 4800.00 | 12000.00 | 310000.00 | ▇▁▁▁▁ |
| glass_bottles | 264 | 0.74 | 20.92 | 15.08 | 0.00 | 10.00 | 18.00 | 28.00 | 110.00 | ▇▃▁▁▁ |
| plastic_bags | 1 | 1.00 | 927.03 | 1388.81 | 0.00 | 220.00 | 470.00 | 1115.00 | 13450.00 | ▇▁▁▁▁ |
| wrappers | 118 | 0.89 | 2246.28 | 2638.16 | 0.00 | 900.00 | 1440.00 | 2580.00 | 20100.00 | ▇▁▁▁▁ |
| sports_balls | 381 | 0.63 | 13.98 | 9.96 | 0.00 | 6.00 | 12.00 | 20.00 | 56.00 | ▇▆▂▁▁ |
| homes_powered | 22 | 0.98 | 46.96 | 17.64 | 0.00 | 39.50 | 50.17 | 58.33 | 93.67 | ▁▂▇▅▁ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min | max | median | n_unique |
|:---|---:|---:|:---|:---|:---|---:|
| date | 0 | 1 | 2014-05-16 | 2024-06-11 | 2020-12-26 | 540 |

``` r
summary(join3)
```

    ##     dumpster        month                year     
    ##  Min.   :  1.0   Length:1032        Min.   :2014  
    ##  1st Qu.: 86.0   Class :character   1st Qu.:2018  
    ##  Median :199.0   Mode  :character   Median :2020  
    ##  Mean   :245.9                      Mean   :2020  
    ##  3rd Qu.:393.2                      3rd Qu.:2022  
    ##  Max.   :651.0                      Max.   :2024  
    ##                                                   
    ##       date                      weight_tons    volume_cubic_yards
    ##  Min.   :2014-05-16 00:00:00   Min.   :0.610   Min.   : 5.00     
    ##  1st Qu.:2018-04-16 00:00:00   1st Qu.:2.540   1st Qu.:15.00     
    ##  Median :2020-12-26 00:00:00   Median :3.080   Median :15.00     
    ##  Mean   :2020-05-11 15:06:58   Mean   :3.038   Mean   :15.08     
    ##  3rd Qu.:2022-11-04 18:00:00   3rd Qu.:3.553   3rd Qu.:15.00     
    ##  Max.   :2024-06-11 00:00:00   Max.   :5.620   Max.   :20.00     
    ##                                                                  
    ##  plastic_bottles  polystyrene    cigarette_butts  glass_bottles   
    ##  Min.   :   0    Min.   :    0   Min.   :     0   Min.   :  0.00  
    ##  1st Qu.: 980    1st Qu.:  230   1st Qu.:  2800   1st Qu.: 10.00  
    ##  Median :1900    Median :  640   Median :  4800   Median : 18.00  
    ##  Mean   :2201    Mean   : 1383   Mean   : 13296   Mean   : 20.92  
    ##  3rd Qu.:2900    3rd Qu.: 2045   3rd Qu.: 12000   3rd Qu.: 28.00  
    ##  Max.   :9830    Max.   :11528   Max.   :310000   Max.   :110.00  
    ##  NA's   :1       NA's   :1       NA's   :1        NA's   :264     
    ##   plastic_bags      wrappers      sports_balls   homes_powered  
    ##  Min.   :    0   Min.   :    0   Min.   : 0.00   Min.   : 0.00  
    ##  1st Qu.:  220   1st Qu.:  900   1st Qu.: 6.00   1st Qu.:39.50  
    ##  Median :  470   Median : 1440   Median :12.00   Median :50.17  
    ##  Mean   :  927   Mean   : 2246   Mean   :13.98   Mean   :46.96  
    ##  3rd Qu.: 1115   3rd Qu.: 2580   3rd Qu.:20.00   3rd Qu.:58.33  
    ##  Max.   :13450   Max.   :20100   Max.   :56.00   Max.   :93.67  
    ##  NA's   :1       NA's   :118     NA's   :381     NA's   :22     
    ##      name          
    ##  Length:1032       
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ##                    
    ## 

``` r
sum(filter(join3, name == "mrtrash")$weight_tons)
```

    ## [1] 2091.18

``` r
sum(filter(join3, name == "Gwynnda", year == "2022", month == "June")$cigarette_butts)
```

    ## [1] 18120

Our final dataset has 1032 observations and 15 variables, which includes
“dumpster” series number, “month”, “year” and “date” that the dumpster
was collected, and “weight_tons” which means total weights of trash in
the dumpster, “volumn_cubic_yards” which means volumn in cubic yards,
and amount of different trash includes: “plastic_bottles”,
“polystyrene”, cigarette_butts”, “glass_bottles”, “plastic_bags”,
“wrappers”, “sports_balls”, and “homes_powered” describes how many homes
are powered by these energy from trash, and “name” indicates which trash
wheel collected these trash. The total weight of Mr. Trash Wheel is
2091.18 tons, and total number of cigarettes butts in 2022.6 from
Gwynnda is 18120.

# Problem 3

``` r
zipcode <- read_csv(file = "./Data/zillow_data/Zip Codes.csv",
                  ,na = c(".", "NA", ""))
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zillow <- read_csv(file = "./Data/zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",
                  ,na = c(".", "NA", ""))
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
skimr::skim(zipcode)
```

|                                                  |         |
|:-------------------------------------------------|:--------|
| Name                                             | zipcode |
| Number of rows                                   | 322     |
| Number of columns                                | 7       |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |         |
| Column type frequency:                           |         |
| character                                        | 4       |
| numeric                                          | 3       |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |         |
| Group variables                                  | None    |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| County        |         0 |          1.00 |   5 |   8 |     0 |        5 |          0 |
| County Code   |         0 |          1.00 |   3 |   3 |     0 |        5 |          0 |
| File Date     |         0 |          1.00 |   7 |   7 |     0 |        1 |          0 |
| Neighborhood  |       142 |          0.56 |   7 |  29 |     0 |       42 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| State FIPS | 0 | 1 | 36.00 | 0.00 | 36 | 36.00 | 36.0 | 36.00 | 36 | ▁▁▇▁▁ |
| County FIPS | 0 | 1 | 36059.77 | 21.14 | 36005 | 36061.00 | 36061.0 | 36081.00 | 36085 | ▂▁▂▇▅ |
| ZipCode | 0 | 1 | 10651.28 | 573.98 | 10001 | 10128.25 | 10382.5 | 11237.75 | 11697 | ▇▂▁▃▃ |

``` r
skimr::skim(zillow)
```

|                                                  |        |
|:-------------------------------------------------|:-------|
| Name                                             | zillow |
| Number of rows                                   | 149    |
| Number of columns                                | 125    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |        |
| Column type frequency:                           |        |
| character                                        | 6      |
| numeric                                          | 119    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |        |
| Group variables                                  | None   |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| RegionType    |         0 |             1 |   3 |   3 |     0 |        1 |          0 |
| StateName     |         0 |             1 |   2 |   2 |     0 |        1 |          0 |
| State         |         0 |             1 |   2 |   2 |     0 |        1 |          0 |
| City          |         0 |             1 |   8 |   8 |     0 |        1 |          0 |
| Metro         |         0 |             1 |  37 |  37 |     0 |        1 |          0 |
| CountyName    |         0 |             1 |  12 |  15 |     0 |        5 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| RegionID | 0 | 1.00 | 66415.47 | 38988.56 | 61615.00 | 61657.00 | 62005.00 | 62045.00 | 399546.00 | ▇▁▁▁▁ |
| SizeRank | 0 | 1.00 | 2533.31 | 4027.80 | 4.00 | 142.00 | 1025.00 | 3485.00 | 30490.00 | ▇▁▁▁▁ |
| RegionName | 0 | 1.00 | 10737.47 | 573.95 | 10001.00 | 10044.00 | 10473.00 | 11233.00 | 11693.00 | ▇▃▁▆▅ |
| 2015-01-31 | 95 | 0.36 | 2738.89 | 616.65 | 1621.01 | 2174.36 | 2735.61 | 3235.03 | 4023.76 | ▆▅▅▇▂ |
| 2015-02-28 | 94 | 0.37 | 2738.68 | 620.51 | 1667.63 | 2140.74 | 2723.87 | 3241.67 | 4022.12 | ▆▅▅▇▂ |
| 2015-03-31 | 92 | 0.38 | 2735.00 | 623.80 | 1682.15 | 2183.60 | 2682.60 | 3251.31 | 4040.42 | ▆▇▆▇▂ |
| 2015-04-30 | 90 | 0.40 | 2736.80 | 638.32 | 1701.87 | 2184.40 | 2676.21 | 3295.81 | 4118.17 | ▇▇▆▇▂ |
| 2015-05-31 | 89 | 0.40 | 2745.61 | 647.01 | 1708.65 | 2186.12 | 2705.62 | 3325.51 | 4171.55 | ▇▆▆▇▂ |
| 2015-06-30 | 88 | 0.41 | 2752.35 | 659.94 | 1721.82 | 2169.14 | 2741.79 | 3331.37 | 4235.90 | ▇▅▆▆▂ |
| 2015-07-31 | 88 | 0.41 | 2769.38 | 650.20 | 1722.57 | 2203.41 | 2752.92 | 3327.30 | 4219.73 | ▇▆▆▆▂ |
| 2015-08-31 | 88 | 0.41 | 2781.04 | 648.73 | 1700.30 | 2221.24 | 2779.25 | 3333.26 | 4185.94 | ▇▇▆▇▂ |
| 2015-09-30 | 88 | 0.41 | 2788.32 | 643.56 | 1707.19 | 2220.66 | 2786.02 | 3352.88 | 4170.48 | ▇▇▆▇▂ |
| 2015-10-31 | 88 | 0.41 | 2784.88 | 634.82 | 1739.63 | 2218.23 | 2762.96 | 3342.92 | 4094.35 | ▇▆▆▇▂ |
| 2015-11-30 | 89 | 0.40 | 2787.47 | 619.75 | 1765.58 | 2237.67 | 2770.57 | 3318.18 | 4107.52 | ▇▆▆▇▂ |
| 2015-12-31 | 87 | 0.42 | 2723.80 | 652.25 | 1102.40 | 2193.20 | 2686.93 | 3282.30 | 4073.01 | ▁▇▇▇▂ |
| 2016-01-31 | 87 | 0.42 | 2751.78 | 621.82 | 1726.27 | 2213.01 | 2740.78 | 3307.78 | 4113.01 | ▇▇▇▇▂ |
| 2016-02-29 | 85 | 0.43 | 2715.23 | 650.01 | 1141.99 | 2168.15 | 2686.60 | 3309.20 | 4032.82 | ▁▇▆▇▂ |
| 2016-03-31 | 85 | 0.43 | 2728.56 | 652.16 | 1121.80 | 2190.75 | 2684.72 | 3320.87 | 4037.92 | ▁▇▆▇▂ |
| 2016-04-30 | 86 | 0.42 | 2768.58 | 631.41 | 1731.50 | 2248.28 | 2701.50 | 3329.31 | 4081.31 | ▇▇▆▇▂ |
| 2016-05-31 | 78 | 0.48 | 2690.41 | 687.26 | 1116.07 | 2123.89 | 2676.52 | 3266.26 | 4184.26 | ▁▇▅▆▂ |
| 2016-06-30 | 78 | 0.48 | 2707.82 | 688.91 | 1132.13 | 2149.54 | 2693.78 | 3282.66 | 4239.71 | ▁▇▅▆▂ |
| 2016-07-31 | 78 | 0.48 | 2724.10 | 689.72 | 1135.19 | 2155.22 | 2716.96 | 3277.97 | 4272.48 | ▁▇▅▆▂ |
| 2016-08-31 | 78 | 0.48 | 2732.81 | 688.52 | 1139.44 | 2178.75 | 2718.48 | 3296.31 | 4285.70 | ▁▇▅▆▂ |
| 2016-09-30 | 78 | 0.48 | 2733.64 | 682.17 | 1164.41 | 2167.56 | 2724.03 | 3280.84 | 4268.15 | ▁▇▅▆▂ |
| 2016-10-31 | 78 | 0.48 | 2725.85 | 673.67 | 1166.05 | 2161.28 | 2702.16 | 3272.40 | 4224.08 | ▁▇▅▆▂ |
| 2016-11-30 | 78 | 0.48 | 2710.19 | 656.31 | 1181.61 | 2173.78 | 2678.46 | 3249.33 | 4147.98 | ▁▇▅▇▂ |
| 2016-12-31 | 77 | 0.48 | 2675.10 | 648.80 | 1201.44 | 2143.02 | 2657.45 | 3212.24 | 4064.71 | ▂▇▆▇▂ |
| 2017-01-31 | 74 | 0.50 | 2699.73 | 754.77 | 1217.91 | 2142.50 | 2651.78 | 3200.71 | 6040.80 | ▅▇▅▁▁ |
| 2017-02-28 | 74 | 0.50 | 2702.89 | 760.95 | 1237.94 | 2128.60 | 2670.14 | 3207.50 | 6087.51 | ▅▇▅▁▁ |
| 2017-03-31 | 74 | 0.50 | 2714.63 | 762.23 | 1230.28 | 2134.83 | 2688.36 | 3225.06 | 6005.22 | ▅▇▅▁▁ |
| 2017-04-30 | 74 | 0.50 | 2732.82 | 772.79 | 1252.33 | 2160.73 | 2719.87 | 3267.65 | 6095.30 | ▆▇▅▁▁ |
| 2017-05-31 | 75 | 0.50 | 2772.82 | 773.44 | 1263.95 | 2198.58 | 2739.31 | 3304.45 | 6170.41 | ▆▇▅▁▁ |
| 2017-06-30 | 74 | 0.50 | 2776.72 | 790.28 | 1246.35 | 2195.36 | 2736.02 | 3336.25 | 6233.66 | ▅▇▅▁▁ |
| 2017-07-31 | 74 | 0.50 | 2788.74 | 787.76 | 1249.10 | 2206.84 | 2743.75 | 3325.00 | 6175.08 | ▆▇▆▁▁ |
| 2017-08-31 | 74 | 0.50 | 2792.38 | 787.69 | 1231.06 | 2209.40 | 2773.34 | 3323.66 | 6165.48 | ▅▇▆▁▁ |
| 2017-09-30 | 74 | 0.50 | 2787.67 | 787.47 | 1237.41 | 2205.53 | 2757.63 | 3298.43 | 6244.56 | ▅▇▅▁▁ |
| 2017-10-31 | 74 | 0.50 | 2768.42 | 773.85 | 1219.23 | 2203.97 | 2730.75 | 3273.24 | 6229.35 | ▅▇▅▁▁ |
| 2017-11-30 | 74 | 0.50 | 2743.90 | 756.84 | 1225.15 | 2191.21 | 2700.09 | 3222.64 | 6175.02 | ▅▇▅▁▁ |
| 2017-12-31 | 74 | 0.50 | 2735.46 | 729.45 | 1227.68 | 2199.63 | 2704.67 | 3180.62 | 6047.29 | ▃▇▅▁▁ |
| 2018-01-31 | 72 | 0.52 | 2700.41 | 742.07 | 1241.38 | 2170.34 | 2709.16 | 3157.82 | 6012.97 | ▅▇▅▁▁ |
| 2018-02-28 | 71 | 0.52 | 2693.41 | 745.25 | 1257.17 | 2163.13 | 2699.88 | 3167.89 | 5953.84 | ▅▇▅▁▁ |
| 2018-03-31 | 71 | 0.52 | 2710.79 | 747.64 | 1292.34 | 2181.79 | 2729.70 | 3208.68 | 5946.68 | ▅▇▅▁▁ |
| 2018-04-30 | 71 | 0.52 | 2737.43 | 759.10 | 1282.89 | 2204.62 | 2715.30 | 3241.30 | 6070.98 | ▆▇▅▁▁ |
| 2018-05-31 | 71 | 0.52 | 2762.47 | 773.71 | 1317.39 | 2211.30 | 2728.31 | 3272.22 | 6205.13 | ▆▇▅▁▁ |
| 2018-06-30 | 71 | 0.52 | 2785.55 | 785.51 | 1309.97 | 2219.88 | 2754.21 | 3324.04 | 6332.58 | ▆▇▅▁▁ |
| 2018-07-31 | 71 | 0.52 | 2801.25 | 792.28 | 1333.23 | 2232.13 | 2781.00 | 3346.28 | 6347.01 | ▆▇▅▁▁ |
| 2018-08-31 | 71 | 0.52 | 2813.57 | 796.98 | 1292.98 | 2240.59 | 2808.68 | 3364.51 | 6356.25 | ▅▇▅▁▁ |
| 2018-09-30 | 71 | 0.52 | 2816.00 | 800.63 | 1317.57 | 2234.24 | 2808.10 | 3356.33 | 6454.08 | ▅▇▃▁▁ |
| 2018-10-31 | 71 | 0.52 | 2803.88 | 792.71 | 1348.74 | 2235.92 | 2781.19 | 3343.96 | 6431.16 | ▇▇▅▁▁ |
| 2018-11-30 | 71 | 0.52 | 2783.17 | 782.06 | 1384.36 | 2223.02 | 2752.69 | 3322.77 | 6382.98 | ▆▇▃▁▁ |
| 2018-12-31 | 71 | 0.52 | 2763.20 | 762.99 | 1371.82 | 2204.77 | 2736.85 | 3312.09 | 6112.93 | ▇▇▅▁▁ |
| 2019-01-31 | 70 | 0.53 | 2784.08 | 781.79 | 1320.05 | 2219.27 | 2758.81 | 3307.68 | 6143.17 | ▆▇▅▁▁ |
| 2019-02-28 | 70 | 0.53 | 2797.49 | 793.08 | 1308.68 | 2243.49 | 2775.87 | 3323.56 | 6298.91 | ▆▇▅▁▁ |
| 2019-03-31 | 69 | 0.54 | 2811.46 | 804.79 | 1312.28 | 2261.38 | 2776.82 | 3341.15 | 6442.21 | ▇▇▃▁▁ |
| 2019-04-30 | 70 | 0.53 | 2847.91 | 809.90 | 1346.87 | 2272.87 | 2807.74 | 3376.63 | 6506.51 | ▆▇▃▁▁ |
| 2019-05-31 | 69 | 0.54 | 2860.72 | 823.51 | 1355.27 | 2283.46 | 2823.05 | 3406.93 | 6503.63 | ▇▇▅▁▁ |
| 2019-06-30 | 69 | 0.54 | 2887.24 | 837.12 | 1373.36 | 2301.44 | 2851.59 | 3432.79 | 6615.79 | ▆▇▃▁▁ |
| 2019-07-31 | 69 | 0.54 | 2909.51 | 841.40 | 1366.54 | 2297.51 | 2875.42 | 3474.66 | 6660.57 | ▆▇▃▁▁ |
| 2019-08-31 | 69 | 0.54 | 2922.32 | 843.04 | 1375.78 | 2296.81 | 2893.00 | 3480.74 | 6642.74 | ▆▇▅▁▁ |
| 2019-09-30 | 69 | 0.54 | 2926.67 | 844.73 | 1367.59 | 2292.81 | 2897.70 | 3475.02 | 6667.69 | ▆▇▅▁▁ |
| 2019-10-31 | 69 | 0.54 | 2923.21 | 837.07 | 1373.97 | 2281.39 | 2893.77 | 3436.20 | 6633.50 | ▆▇▅▁▁ |
| 2019-11-30 | 69 | 0.54 | 2906.60 | 821.62 | 1379.23 | 2289.37 | 2863.09 | 3422.59 | 6491.67 | ▆▇▃▁▁ |
| 2019-12-31 | 69 | 0.54 | 2890.44 | 810.19 | 1380.27 | 2296.77 | 2837.01 | 3417.75 | 6373.21 | ▆▇▅▁▁ |
| 2020-01-31 | 67 | 0.55 | 2863.15 | 806.67 | 1375.98 | 2238.21 | 2754.52 | 3421.21 | 6334.21 | ▆▇▅▁▁ |
| 2020-02-29 | 67 | 0.55 | 2880.94 | 814.25 | 1376.83 | 2257.07 | 2774.39 | 3434.59 | 6446.17 | ▆▇▅▁▁ |
| 2020-03-31 | 67 | 0.55 | 2902.62 | 809.68 | 1652.83 | 2281.12 | 2794.68 | 3449.31 | 6525.56 | ▇▆▃▁▁ |
| 2020-04-30 | 65 | 0.56 | 2871.53 | 814.34 | 1417.88 | 2278.38 | 2725.93 | 3432.12 | 6554.35 | ▇▇▃▁▁ |
| 2020-05-31 | 60 | 0.60 | 2824.85 | 797.36 | 1438.81 | 2244.76 | 2618.54 | 3399.38 | 6552.07 | ▇▇▃▁▁ |
| 2020-06-30 | 59 | 0.60 | 2780.28 | 778.39 | 1436.30 | 2228.92 | 2576.02 | 3340.70 | 6508.90 | ▇▇▃▁▁ |
| 2020-07-31 | 59 | 0.60 | 2747.37 | 751.62 | 1433.48 | 2227.13 | 2546.24 | 3272.57 | 6357.30 | ▇▇▂▁▁ |
| 2020-08-31 | 61 | 0.59 | 2664.10 | 704.84 | 1426.36 | 2193.54 | 2482.48 | 3168.14 | 6098.40 | ▇▇▂▁▁ |
| 2020-09-30 | 60 | 0.60 | 2602.67 | 664.76 | 1424.97 | 2171.91 | 2421.55 | 3076.86 | 5935.65 | ▇▇▂▁▁ |
| 2020-10-31 | 58 | 0.61 | 2565.34 | 645.68 | 1417.83 | 2128.69 | 2392.85 | 3020.23 | 5923.50 | ▇▇▁▁▁ |
| 2020-11-30 | 57 | 0.62 | 2529.75 | 624.45 | 1417.19 | 2098.36 | 2351.11 | 2934.61 | 5773.41 | ▇▇▂▁▁ |
| 2020-12-31 | 55 | 0.63 | 2494.72 | 614.06 | 1421.98 | 2074.17 | 2310.77 | 2888.06 | 5615.51 | ▇▇▂▁▁ |
| 2021-01-31 | 54 | 0.64 | 2480.30 | 598.58 | 1420.38 | 2055.68 | 2293.72 | 2878.43 | 5421.61 | ▇▇▂▁▁ |
| 2021-02-28 | 52 | 0.65 | 2479.11 | 608.17 | 1451.03 | 2036.81 | 2303.14 | 2910.75 | 5538.09 | ▇▇▂▁▁ |
| 2021-03-31 | 51 | 0.66 | 2499.28 | 627.95 | 1454.84 | 2046.42 | 2328.16 | 2955.35 | 5753.05 | ▇▇▁▁▁ |
| 2021-04-30 | 50 | 0.66 | 2528.88 | 661.37 | 1477.05 | 2058.32 | 2310.20 | 3004.68 | 5966.01 | ▇▆▁▁▁ |
| 2021-05-31 | 50 | 0.66 | 2574.05 | 706.19 | 1467.01 | 2061.52 | 2331.10 | 3086.45 | 6235.35 | ▇▅▁▁▁ |
| 2021-06-30 | 49 | 0.67 | 2629.20 | 752.72 | 1471.03 | 2085.45 | 2369.24 | 3179.77 | 6439.81 | ▇▅▁▁▁ |
| 2021-07-31 | 49 | 0.67 | 2698.82 | 808.64 | 1469.99 | 2103.19 | 2400.75 | 3275.72 | 6739.81 | ▇▅▂▁▁ |
| 2021-08-31 | 49 | 0.67 | 2761.47 | 860.94 | 1444.35 | 2146.73 | 2440.56 | 3381.35 | 6935.64 | ▇▅▂▁▁ |
| 2021-09-30 | 50 | 0.66 | 2821.51 | 897.48 | 1440.93 | 2170.78 | 2481.20 | 3477.04 | 7073.61 | ▇▅▂▁▁ |
| 2021-10-31 | 46 | 0.69 | 2850.89 | 946.01 | 1453.17 | 2118.53 | 2444.25 | 3556.60 | 7146.54 | ▇▅▂▁▁ |
| 2021-11-30 | 46 | 0.69 | 2872.78 | 962.09 | 1444.50 | 2123.04 | 2467.72 | 3607.30 | 7151.12 | ▇▅▂▁▁ |
| 2021-12-31 | 42 | 0.72 | 2850.18 | 967.95 | 1430.83 | 2094.84 | 2461.37 | 3598.20 | 7168.36 | ▇▅▂▁▁ |
| 2022-01-31 | 42 | 0.72 | 2874.67 | 971.54 | 1439.22 | 2125.42 | 2481.42 | 3640.12 | 7120.40 | ▇▃▂▁▁ |
| 2022-02-28 | 42 | 0.72 | 2903.53 | 981.52 | 1457.82 | 2147.24 | 2519.14 | 3658.82 | 7231.09 | ▇▃▂▁▁ |
| 2022-03-31 | 38 | 0.74 | 2925.25 | 985.20 | 1500.96 | 2177.93 | 2552.71 | 3664.95 | 7271.80 | ▇▃▂▁▁ |
| 2022-04-30 | 37 | 0.75 | 2958.19 | 1004.49 | 1533.41 | 2178.02 | 2561.75 | 3685.47 | 7381.56 | ▇▃▂▁▁ |
| 2022-05-31 | 34 | 0.77 | 2983.66 | 1022.21 | 1567.76 | 2188.36 | 2591.05 | 3771.72 | 7384.81 | ▇▃▂▁▁ |
| 2022-06-30 | 34 | 0.77 | 3033.94 | 1046.58 | 1567.79 | 2204.05 | 2671.53 | 3812.99 | 7517.17 | ▇▃▃▁▁ |
| 2022-07-31 | 34 | 0.77 | 3081.91 | 1060.54 | 1548.81 | 2213.42 | 2728.59 | 3867.63 | 7565.49 | ▇▃▃▁▁ |
| 2022-08-31 | 34 | 0.77 | 3108.83 | 1068.52 | 1522.13 | 2220.53 | 2739.15 | 3932.60 | 7630.87 | ▇▅▃▁▁ |
| 2022-09-30 | 34 | 0.77 | 3121.11 | 1063.23 | 1552.40 | 2257.63 | 2772.60 | 3925.17 | 7645.88 | ▇▅▃▁▁ |
| 2022-10-31 | 34 | 0.77 | 3112.96 | 1049.32 | 1568.25 | 2281.30 | 2794.47 | 3928.19 | 7663.88 | ▇▅▃▁▁ |
| 2022-11-30 | 33 | 0.78 | 3087.73 | 1022.44 | 1602.94 | 2318.01 | 2738.05 | 3879.23 | 7604.98 | ▇▃▂▁▁ |
| 2022-12-31 | 34 | 0.77 | 3074.90 | 1000.42 | 1584.66 | 2303.41 | 2724.50 | 3841.63 | 7477.51 | ▇▅▃▁▁ |
| 2023-01-31 | 34 | 0.77 | 3075.26 | 984.52 | 1585.09 | 2362.60 | 2719.91 | 3840.05 | 7480.99 | ▇▃▃▁▁ |
| 2023-02-28 | 29 | 0.81 | 3053.87 | 985.01 | 1605.23 | 2367.22 | 2709.04 | 3783.99 | 7482.95 | ▇▃▂▁▁ |
| 2023-03-31 | 30 | 0.80 | 3083.47 | 1002.68 | 1631.59 | 2357.53 | 2722.54 | 3831.45 | 7720.44 | ▇▃▂▁▁ |
| 2023-04-30 | 29 | 0.81 | 3104.13 | 1025.33 | 1644.54 | 2352.59 | 2728.11 | 3863.06 | 7834.27 | ▇▃▂▁▁ |
| 2023-05-31 | 28 | 0.81 | 3123.89 | 1046.25 | 1632.41 | 2353.86 | 2751.55 | 3897.38 | 8021.65 | ▇▃▂▁▁ |
| 2023-06-30 | 28 | 0.81 | 3159.17 | 1058.53 | 1638.25 | 2380.42 | 2791.35 | 3948.54 | 7996.38 | ▇▃▂▁▁ |
| 2023-07-31 | 26 | 0.83 | 3173.69 | 1057.72 | 1654.29 | 2393.97 | 2817.25 | 3941.01 | 7956.49 | ▇▃▂▁▁ |
| 2023-08-31 | 26 | 0.83 | 3191.72 | 1053.15 | 1694.29 | 2406.93 | 2808.64 | 3977.61 | 7936.27 | ▇▃▂▁▁ |
| 2023-09-30 | 26 | 0.83 | 3202.59 | 1035.56 | 1663.45 | 2430.78 | 2794.89 | 3971.04 | 7905.63 | ▇▃▂▁▁ |
| 2023-10-31 | 27 | 0.82 | 3191.83 | 1025.22 | 1728.50 | 2397.50 | 2810.44 | 3999.91 | 7904.82 | ▇▃▂▁▁ |
| 2023-11-30 | 26 | 0.83 | 3167.28 | 1000.65 | 1714.51 | 2450.49 | 2771.01 | 3912.46 | 7862.90 | ▇▃▂▁▁ |
| 2023-12-31 | 24 | 0.84 | 3149.41 | 979.98 | 1777.78 | 2457.89 | 2756.74 | 3890.84 | 7748.68 | ▇▃▂▁▁ |
| 2024-01-31 | 23 | 0.85 | 3152.82 | 966.11 | 1754.98 | 2494.70 | 2774.16 | 3919.25 | 7682.28 | ▇▃▂▁▁ |
| 2024-02-29 | 24 | 0.84 | 3183.38 | 970.57 | 1812.77 | 2505.21 | 2782.31 | 3986.47 | 7714.36 | ▇▃▂▁▁ |
| 2024-03-31 | 23 | 0.85 | 3219.51 | 987.70 | 1954.76 | 2522.83 | 2815.90 | 4016.49 | 7990.80 | ▇▃▁▁▁ |
| 2024-04-30 | 22 | 0.85 | 3248.93 | 1005.08 | 1934.65 | 2524.57 | 2824.02 | 4033.58 | 8102.98 | ▇▃▁▁▁ |
| 2024-05-31 | 19 | 0.87 | 3268.42 | 1016.92 | 1915.51 | 2557.16 | 2817.48 | 4038.27 | 8182.68 | ▇▃▂▁▁ |
| 2024-06-30 | 16 | 0.89 | 3273.09 | 1036.20 | 1963.07 | 2547.18 | 2827.31 | 4054.32 | 8195.11 | ▇▃▁▁▁ |
| 2024-07-31 | 6 | 0.96 | 3291.33 | 1084.00 | 1995.07 | 2538.65 | 2841.97 | 4052.06 | 8213.98 | ▇▃▁▁▁ |
| 2024-08-31 | 0 | 1.00 | 3279.23 | 1073.50 | 2016.67 | 2566.11 | 2869.07 | 3950.79 | 8422.62 | ▇▃▁▁▁ |

``` r
filter(zillow, )
```

    ## # A tibble: 149 × 125
    ##    RegionID SizeRank RegionName RegionType StateName State City     Metro       
    ##       <dbl>    <dbl>      <dbl> <chr>      <chr>     <chr> <chr>    <chr>       
    ##  1    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  2    62093        7      11385 zip        NY        NY    New York New York-Ne…
    ##  3    62019        9      11208 zip        NY        NY    New York New York-Ne…
    ##  4    62046       16      11236 zip        NY        NY    New York New York-Ne…
    ##  5    61807       17      10467 zip        NY        NY    New York New York-Ne…
    ##  6    62085       18      11373 zip        NY        NY    New York New York-Ne…
    ##  7    62037       19      11226 zip        NY        NY    New York New York-Ne…
    ##  8    62018       20      11207 zip        NY        NY    New York New York-Ne…
    ##  9    61639       29      10025 zip        NY        NY    New York New York-Ne…
    ## 10    62025       32      11214 zip        NY        NY    New York New York-Ne…
    ## # ℹ 139 more rows
    ## # ℹ 117 more variables: CountyName <chr>, `2015-01-31` <dbl>,
    ## #   `2015-02-28` <dbl>, `2015-03-31` <dbl>, `2015-04-30` <dbl>,
    ## #   `2015-05-31` <dbl>, `2015-06-30` <dbl>, `2015-07-31` <dbl>,
    ## #   `2015-08-31` <dbl>, `2015-09-30` <dbl>, `2015-10-31` <dbl>,
    ## #   `2015-11-30` <dbl>, `2015-12-31` <dbl>, `2016-01-31` <dbl>,
    ## #   `2016-02-29` <dbl>, `2016-03-31` <dbl>, `2016-04-30` <dbl>, …

``` r
zipcode <- janitor::clean_names(zipcode)

zillow <- janitor::clean_names(zillow) |>
  rename(zip_code = "region_name")

duplicate <- filter(janitor::get_dupes(zipcode, zip_code), county == "New York") |>
  select(-dupe_count)
zipcode <- anti_join(zipcode, duplicate, by = names(duplicate)) #delete two duplicated rows which have same zipcode but different county.

join4 <- left_join(zillow, zipcode, by = "zip_code") |>
  select(-file_date) #delete some useless variables

not_included_zip <- anti_join(zipcode, zillow, by = "zip_code") #make a dataframe which includes zipcodes not included in zillow
skim(zipcode)
```

|                                                  |         |
|:-------------------------------------------------|:--------|
| Name                                             | zipcode |
| Number of rows                                   | 320     |
| Number of columns                                | 7       |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |         |
| Column type frequency:                           |         |
| character                                        | 4       |
| numeric                                          | 3       |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |         |
| Group variables                                  | None    |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| county        |         0 |          1.00 |   5 |   8 |     0 |        5 |          0 |
| county_code   |         0 |          1.00 |   3 |   3 |     0 |        5 |          0 |
| file_date     |         0 |          1.00 |   7 |   7 |     0 |        1 |          0 |
| neighborhood  |       142 |          0.56 |   7 |  29 |     0 |       42 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| state_fips | 0 | 1 | 36.00 | 0.00 | 36 | 36.0 | 36.0 | 36.00 | 36 | ▁▁▇▁▁ |
| county_fips | 0 | 1 | 36059.76 | 21.21 | 36005 | 36061.0 | 36061.0 | 36081.00 | 36085 | ▂▁▂▇▅ |
| zip_code | 0 | 1 | 10650.15 | 574.86 | 10001 | 10127.5 | 10313.5 | 11238.25 | 11697 | ▇▂▁▃▃ |

``` r
skim(not_included_zip)
```

|                                                  |                  |
|:-------------------------------------------------|:-----------------|
| Name                                             | not_included_zip |
| Number of rows                                   | 171              |
| Number of columns                                | 7                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                  |
| Column type frequency:                           |                  |
| character                                        | 4                |
| numeric                                          | 3                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                  |
| Group variables                                  | None             |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| county        |         0 |           1.0 |   5 |   8 |     0 |        5 |          0 |
| county_code   |         0 |           1.0 |   3 |   3 |     0 |        5 |          0 |
| file_date     |         0 |           1.0 |   7 |   7 |     0 |        1 |          0 |
| neighborhood  |       137 |           0.2 |   7 |  26 |     0 |       14 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| state_fips | 0 | 1 | 36.00 | 0.00 | 36 | 36.0 | 36 | 36 | 36 | ▁▁▇▁▁ |
| county_fips | 0 | 1 | 36063.47 | 16.67 | 36005 | 36061.0 | 36061 | 36081 | 36085 | ▁▁▁▇▃ |
| zip_code | 0 | 1 | 10574.07 | 566.40 | 10008 | 10132.5 | 10265 | 11246 | 11697 | ▇▁▁▁▂ |

``` r
nrow(not_included_zip)
```

    ## [1] 171

``` r
final_join4 <- pivot_longer(join4, 
    x2015_01_31:x2024_08_31,
    names_to = "time",
    values_to = "zillow_val"
)
final_join4 <- drop_na(final_join4, zillow_val) #In final dataset, we keep the NA neighborhood, remove the NA zillow value to remove some useless time point.

length(unique(na.omit(final_join4$neighborhood))) #ignore NA neighborhood when calculate how many different neighborhood
```

    ## [1] 42

In our final dataset, we have 10450 observations depends on the date we
observe, because we have too many missing data in many dates for one
zipcode, so I just treat different dates as a variable to make this
final dataset easier to be read. It includes 149 different zipcodes
which is same as number of rows of zillow. There are 42 different
neighborhood.

By analyzing the not_included_zip, the zipcode mainly from county code
05, 41, 61, 81 are not included in the zillow dataset. I think there are
two possible reasons:

First, by analyzing the not_included_zip, I found there are 137 missing
values of neighborhood in Zipcodes not included in the zillow dataset,
and there are totally 142 missing values of neighborhood in zipcode
dataset. Because of that, I think maybe zillow dropped these zipcodes
because of the incomplete of data.

Second, thew county code of these zipcodes are mainly gathering around
05, 41, 61, 81, so it is possible that zillow didn’t have enough people
to collect data in these areas in New York.

``` r
diff_table <- tibble(diff = join4$x2020_01_31 - join4$x2021_01_31, zipcode = join4$zip_code, county_name = join4$county_name, neighborhood = join4$neighborhood) |>
  drop_na() |>
  arrange(desc(diff))
top10 <- diff_table[1:10,]
top10
```

    ## # A tibble: 10 × 4
    ##     diff zipcode county_name     neighborhood                 
    ##    <dbl>   <dbl> <chr>           <chr>                        
    ##  1  913.   10007 New York County Lower Manhattan              
    ##  2  714.   10009 New York County Lower East Side              
    ##  3  712.   10016 New York County Gramercy Park and Murray Hill
    ##  4  710.   10001 New York County Chelsea and Clinton          
    ##  5  710.   10002 New York County Lower East Side              
    ##  6  706.   10004 New York County Lower Manhattan              
    ##  7  698.   10038 New York County Lower Manhattan              
    ##  8  686.   10012 New York County Greenwich Village and Soho   
    ##  9  685.   10010 New York County Gramercy Park and Murray Hill
    ## 10  673.   10003 New York County Lower East Side

Based on the top10 housing decreasing prices table, the lower manhattan,
lower east side had the worst decreasing of housing price. It may caused
by the disease distribution in New York, the place had more patients may
got a worse housing price.
